### ISSUE TITLE
EXC_BAD_ACCESS at -[RKResponseDescriptor matchesURL:]

### ISSUE THREAD

**Issue by wiruzx** [RestKit/RestKit#2188]
`EXC_BAD_ACCESS` `KERN_INVALID_ADDRESS` 
in RKResponseDescriptor.m at line 132

Here's my backtrace:

```
Thread : Crashed: org.restkit.network.object-request-operation-queue
0  libobjc.A.dylib                0x0000000194a10174 objc_release + 20
1  Project                       0x00000001004ed518 -[RKResponseDescriptor matchesURL:] (RKResponseDescriptor.m:132)
2  Project                       0x00000001004ed58c -[RKResponseDescriptor matchesResponse:] (RKResponseDescriptor.m:136)
3  Project                       0x00000001004eeafc __61-[RKResponseMapperOperation buildMatchingResponseDescriptors]_block_invoke (RKResponseMapperOperation.m:225)
4  CoreFoundation                 0x0000000182f9e3d4 __NSArrayGetIndexesPassingTest + 576
5  Project                       0x00000001004eea24 -[RKResponseMapperOperation buildMatchingResponseDescriptors] (RKResponseMapperOperation.m:224)
6  Project                       0x00000001004ee3c4 -[RKResponseMapperOperation initWithRequest:response:data:responseDescriptors:] (RKResponseMapperOperation.m:190)
7  Project                       0x00000001004f5b3c -[RKManagedObjectRequestOperation performMappingOnResponseWithCompletionBlock:] (RKManagedObjectRequestOperation.m:591)
8  Project                       0x00000001004e9e70 __35-[RKObjectRequestOperation execute]_block_invoke (RKObjectRequestOperation.m:517)
9  Project                       0x000000010051135c __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke143 (AFHTTPRequestOperation.m:283)
10 libdispatch.dylib              0x0000000195071994 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x0000000195071954 _dispatch_client_callout + 16
12 libdispatch.dylib              0x000000019507ab70 _dispatch_async_redirect_invoke + 1604
13 libdispatch.dylib              0x0000000195071954 _dispatch_client_callout + 16
14 libdispatch.dylib              0x000000019507e780 _dispatch_root_queue_drain + 1848
15 libdispatch.dylib              0x000000019507fc4c _dispatch_worker_thread3 + 108
16 libsystem_pthread.dylib        0x000000019525122c _pthread_wqthread + 816
```

**Comment by segiddins** [comment]
Could you please provide a reproducible case of this crash? Otherwise, I can't really do much about it.

**Comment by wiruzx** [comment]
Hey @segiddins,
Unfortunately, I can't reproduce it myself, but we've got over 1000 crash-reports with this bug from Crashlytics.

**Comment by Vyazovoy** [comment]
Hello. @segiddins @wiruzx I have same reports time to time about a year but I can't figure out what happened. Also can't reproduce. I use standard RestKit configuration (with CoreData) and use response descriptors only in mapping initialisation.

**Comment by segiddins** [comment]
It's possible this is fixed on master with the PR I just merged, but I can't do anything without a reproducible test case.

**Comment by wiruzx** [comment]
Thanks @segiddins, I hope this will help

**Comment by rahulkas** [comment]
Issue is still occuring in V0.23.3 with same backtrace and it is happening 1 out of 10 times.
